### PR TITLE
Fix some issues

### PR DESCRIPTION
**Pull request by jaredlll08**

### CODE REVIEW

**Comment by dmillerw** [comment]
I may not be the maintainer anymore, but try to use 4 spaces instead of tabs when indenting your code. The code you've worked on now looks strange compared to the rest of it, in regards to formatting

**Comment by jaredlll08** [comment]
Yea, I have formatter, that is probably it, so should I format it to default eclipse? or format the whole code to my formatter? (As far as I know, or according to @nbogle I am the new maintainer, but I don't want you to hate looking at your code :/ )

**Comment by dmillerw** [comment]
Generally the majority of people will use 4 spaces for indentation. I can only ask, but it is up to you

**Comment by Katelyn-SN** [comment]
I extremely recommend the use of 4 spaces instead of tab.

**Comment by jaredlll08** [comment]
Sorry for the necro, closing old PRs

**Pull request closed without merging**
